### ISSUE TITLE
sensu client socket

### ISSUE THREAD

**Issue by agent462** [agent462/sensu-cli#2]
from @joemiller: 
what do you think about extending it beyond just the rest api and providing interfaces to other things like the sensu client socket? eg: sensu event create NAME STATUS OUTPUT (options) would be equiv to: echo '{"name": "some_check", "status": 2, "output": "check output"}' | nc 127.0.0.1 3030

**Comment by jjuarez** [comment]
+1 definitely

**Comment by agent462** [comment]
I wrote a majority of the code to do this today.  I should have this out soon.

**Comment by agent462** [comment]
Haven't pushed a release yet but initial version of `sensu-cli socket create` and `sensu-cli socket raw` are in master.

**Comment by agent462** [comment]
released and in rubygems https://github.com/agent462/sensu-cli/releases/tag/v0.7.0
