### ISSUE TITLE
Need more examples to howto complete the settings.rb

### ISSUE THREAD

**Issue by HelioCampos** [agent462/sensu-cli#27]
The documentation about the setting.rb is too simples. For example:
 - The host variable: Does not explain witch host. It could be the local, the rabbbitmq, or the redis host. Also, i'm getting the message "An HTTP error occurred.  Check your settings. Connection refused - connect(2)" and cannot find doc that explain the error.
 - The user variable: Does not explain witch user it need to connect to.

**Comment by agent462** [comment]
The host and user are for the Sensu API.  I will clarify in the documentation.  

Connection refused is simply whatever you are trying to connect to is refusing the connection.  I would check the port or host as clarified in the first sentence.

**Comment by agent462** [comment]
https://github.com/agent462/sensu-cli/commit/581f0735f921b4625c8e7f71dae21567c7565bff
