### ISSUE TITLE
unsilence command

### ISSUE THREAD

**Issue by loganrosen** [agent462/sensu-cli#38]
There isn't a specific unsilence command. I'm guessing this could be done with a stash delete of silence/{client,check}, based on a cursory look at the code.

But it would be cool if that were rolled into a command to unsilence a client or check, since the end user isn't necessarily going to know the stash path (and I haven't tested that the above works).

**Comment by agent462** [comment]
Obvious and good idea.  I'll add this in a future release.

**Comment by windowsrefund** [comment]
With Sensu 1.2.0, the silenced event doesn't appear to be created as a stash. That means it doesn't show up in the output of ``sensu-cli stash list`` and is therefore, not a candidate for deletion via ``sensu-cli stash delete``

**Comment by agent462** [comment]
As I never got around to adding this and the stash method is being deprecated.  I am closing this.
