### ISSUE TITLE
Add datacentre field to stashes

### ISSUE THREAD

**Issue by madAndroid** [agent462/sensu-cli#45]
Uchiwa has the concept of datacentre, it would be great if the sensu-cli was able to set this field during stash creation. The use case I've currently got: creating silence stashes for EC2 instances that are coming up during instance creation, in a different datacentre to the Jenkins master that I'm creating the silence stashes from.

**Comment by madAndroid** [comment]
I'm not sure if this is even possible, the Sensu documentation is not very clear on this, but it would be great to have if it is possible.

**Comment by agent462** [comment]
The data center aspect is in Uchiwa only based on configuring Uchiwa to talk to multiple Sensu servers.  If this is for pure Uchiwa display purposes, all you need to do is make sure the Jenkins server is pointing at the correct Sensu server when creating the stash.  Once the stash is created against the Sensu server responsible for the client you would see the Stash in Uchiwa in the correct DC.

If you need something beyond that can be automated, we should extend sensu-cli stash create to be able to pass in raw json.  Today it opens up the default editor to create.

**Comment by madAndroid** [comment]
Yes, thanks for the explanation - that does make sense. I was expecting the Sensu server I was creating the stashes on, to be able to create them for the other DCs, because the other DCs are not up at that time - I'll look at hitting the API on the Server nodes once they are provisioned, from the Jenkins host.
