### ISSUE TITLE
Should the tool not connect to rabbitmq (5672) instead of the api (4567)?

### ISSUE THREAD

**Issue by 030** [agent462/sensu-cli#46]
I would like to trigger an event on a client. 5672 is one of the few ports that is open on the sensu-server.

**Comment by agent462** [comment]
The main goal of sensu-cli is to interact with the sensu server via the api.  Functionality was added to create an event to the sensu client via socket.  Please see the sensu socket docs; https://github.com/agent462/sensu-cli#socket
