### ISSUE TITLE
Cannot create a critical in uchiwa

### ISSUE THREAD

**Issue by 030** [agent462/sensu-cli#50]
```
sensu-cli socket create  -n bla -s 2 -o haha
```

results in:

```
UDP Socket Message Sent
```

but no check appeared in uchiwa

**Comment by agent462** [comment]
You have to make sure you're making the socket connection on a server that is running sensu-client.  sensu-cli just assists in the creation of these arbitrary checks by administrators and scripts.  It's essentially the same as doing:
echo '{"name": "app_01", "output": "could not connect to mysql", "status": 1}' | nc localhost 3030

https://sensuapp.org/docs/latest/reference/clients.html#client-socket-input

**Comment by 030** [comment]
Thank you.
