### ISSUE TITLE
Add capability to use new silence API

### ISSUE THREAD

**Issue by madAndroid** [agent462/sensu-cli#53]
Hi,

First of all, great tool!
Would it be possible to switch the silence functionality to use the new silence API, available since `0.26.x`? https://sensuapp.org/docs/0.26/api/silenced-api.html

The older stash method of silencing alerts is deprecated from this version onwards.
https://github.com/sensu/sensu/issues/1328

**Comment by agent462** [comment]
I have just committed to master full support for the silenced api.  There is a new command "silenced" to maintain compatibility with users pre 0.26

Would you mind poking around and testing?

          ** Silenced Commands **
          sensu-cli silenced list (OPTIONS)
          sensu-cli silenced create (OPTIONS)
          sensu-cli silenced clear (OPTIONS)

**Comment by madAndroid** [comment]
Awesome, thank you! looks like this is working as expected:
```
[andrstan@core-infradev-aeuw1-bastion-02fc07877e370b461 ~]$ bundle exec sensu-cli silenced create -c $(facter fqdn)
The silence has been created.
```
```
[andrstan@core-infradev-aeuw1-bastion-02fc07877e370b461 ~]$ bundle exec sensu-cli silenced list
-------
id:  *:core-infradev-aeuw1-bastion-02fc07877e370b461.[REDACTED]
subscription:
check:  core-infradev-aeuw1-bastion-02fc07877e370b461.[REDACTED]
reason:  Silenced via API - no reason given
creator:  andrstan
expire_on_resolve:  false
expire:  -1
```
Could you please create a new release with these changes included?

**Comment by agent462** [comment]
New version pushed: https://rubygems.org/gems/sensu-cli/versions/0.8.0

**Comment by windowsrefund** [comment]
I'm running version 0.9.0 but my silenced events are not showing up when I run ``sensu-cli silenced list``. Also, I just noticed that the --format option does not appear to be supported for the silenced subcommand. Not sure how one would go about deleting silenced events older than a paricular number of hours (as discussed in the README using the old stash approach).
