### ISSUE TITLE
please update the project rubygems

### ISSUE THREAD

**Issue by y0y0z** [agent462/sensu-cli#55]
asking nicely rather than creating a pull request (let me know whether you prefer that i will submit a pull request)...

**please** update the rubygems in the project.

```
Bundler could not find compatible versions for gem "rainbow":
  In Gemfile:
    rubocop (= 0.50.0) was resolved to 0.50.0, which depends on
      rainbow (< 3.0, >= 2.2.2)

    sensu-cli (~> 0) was resolved to 0.0.7, which depends on
      rainbow (= 1.1.4)
```

**Comment by agent462** [comment]
I'll have to do some basic testing.  The last major version of rainbow broke things.

**Comment by y0y0z** [comment]
@agent462: any updates?

**Comment by agent462** [comment]
Thanks; v0.8.1 has been released
https://github.com/agent462/sensu-cli/releases/tag/v0.8.1
